  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_hide_header Strict-Transport-Security;
  # proxy_set_header Host $http_host;
  # we don't want nginx trying to do something clever with
  # redirects, we set the Host: header above already.
  proxy_redirect off;
  set $backend_servers $internal_url:61443;
  proxy_pass https://${backend_servers}${request_uri};
