name: Check DB Models

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  check-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compare borrowed files with upstream
        run: |
          set -euo pipefail

          declare -A files=(
            ["app/models.py"]="https://raw.githubusercontent.com/GSA/datagov-harvester/main/database/models.py"
            ["shared/constants.py"]="https://raw.githubusercontent.com/GSA/datagov-harvester/main/shared/constants.py"
          )

          for path in "${!files[@]}"; do
            echo "Checking ${path}"

            tmp_file="$(mktemp)"
            curl --fail --silent --show-error "${files[$path]}" > "${tmp_file}"

            if ! diff --unified "${tmp_file}" "${path}"; then
              echo "::error file=${path}::${path} has drifted from ${files[$path]}" >&2
              exit 1
            fi

            rm -f "${tmp_file}"
          done
